{{- with .Values.route }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $.Values.app.componentId }}
  labels:
    {{- include "quarkus-template.labels" $ | nindent 4 }}
spec:
  {{- if .host }}
  rules:
    - host: {{ .host }}
      http:
        paths:
          - path: {{ .path | default "/" }}
            pathType: Prefix
            backend:
              service:
                name: {{ $.Values.app.componentId }}
                port:
                  number: {{ $.Values.service.port }}
  {{- else }}
  defaultBackend:
    service:
      name: {{ $.Values.app.componentId }}
      port:
        number: {{ $.Values.service.port }}
  {{- end }}

  {{- if .tls }}
  tls:
    - hosts:
        - {{ .host }}
      secretName: {{ $.Values.tlsSecretName | default "tls-secret" }}
  {{- end }}
{{- end }}
